### ISSUE TITLE
typo on user-docs.rst

### ISSUE THREAD

**Issue by msdisme** [mghpcsim/rtd-nese#8]
On this page: https://github.com/mghpcsim/rtd-nese/blob/main/docs/source/user-docs.rst it says" "As of July 2003"  I believe it is mean to be 2023.   I'll try to do a PR :-)

**Comment by msdisme** [comment]
Looks like I need to do some sw installs to do the PR; not gonna get to this tonight :-/.

**Comment by ohpcsim** [comment]
Thanks for the heads up! I've fixed the typo and also fixed the CI builds so future PRs should build correctly.
